### ISSUE TITLE
How to keep reference to a connection?

### ISSUE THREAD

**Issue by prolic** [amphp/postgres#10]
I need to keep a reference to a specific connection, how can I do this?

Problem is, I want to make use of advisory locks, but this kind of lock is bound to the connection that started the lock, so I need to query the same connection from that point on until I release that lock. Releasing that lock must be done through the same connection again of course.

**Comment by trowski** [comment]
You can use `Pool::extractConnection()` to extract a single connection object from the pool. Once you're done with the connection it is destroyed instead of being put back in the pool

**Comment by prolic** [comment]
Ah great, I must have missed that method, thanks!
