### ISSUE TITLE
Need fix after amphp/sql update

### ISSUE THREAD

**Issue by deadbeat88** [amphp/postgres#15]
After commit e257237b61da7cb25a59a95299e232e9b536d93c (Improve naming) at **amphp/sql** package need to fix **Amp\Postgres\Connection** class.

`Fatal error: Class Amp\Postgres\PgSqlConnection contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Amp\Sql\Link::beginTransaction, Amp\Sql\TransientResource::getLastUsedAt) in vendor/amphp/postgres/src/PgSqlConnection.php on line 14`

**Comment by kelunik** [comment]
Yes, there have been a few renames. Would you like to provide a PR?

**Comment by deadbeat88** [comment]
Ok, I can to provide PR, but later...maybe tommorow at leisure time)
