### ISSUE TITLE
Warning: this package doesn't work on PHP 7.4.1

### ISSUE THREAD

**Issue by enumag** [amphp/postgres#22]
This is ofc a PHP bug which I already [reported](https://bugs.php.net/bug.php?id=79140), I don't think you can do anything about it. Just warning you that this package doesn't work at all on PHP 7.4.1.

Feel free to close this.

**Comment by enumag** [comment]
Note it only seems to happen with the event extension. Using uv instead seems to work.

**Comment by trowski** [comment]
So is it that the event extension doesn't work with 7.4?

**Comment by enumag** [comment]
It was fine until I started using pgsql extension. Also it only happens on ubuntu, alpine is fine.

As for pq extension, that doesn't build for 7.4 at all.

**Comment by enumag** [comment]
Then I have some problem with uv segfaulting on alpine... So far the only way I can work is to use ext-uv locally and ext-event in my alpine Dockerfile. Then it works. For now.

**Comment by trowski** [comment]
So it sounds a bit like the issues are actually with ext-uv and/or ext-event on 7.4.x, more than any specific issue with this package (or amphp in general)?

**Comment by enumag** [comment]
Yeah looks like it. I just encountered the problem only when using this package.

**Comment by trowski** [comment]
Closing this then. Please report the issues on the appropriate extensions, thanks!
