### ISSUE TITLE
Incompatibility with ext-event

### ISSUE THREAD

**Issue by enumag** [amphp/postgres#29]
Ruslan Osmanov has fixed the segfault I was getting when using this with package with ext-event but said that it won't work anyway and that he would need to add pgsql support there - read his comment [here](https://bitbucket.org/osmanov/pecl-event/issues/60/segmentation-fault-on-alpine#comment-57481951).

Can you share some insight if this is really necessary? Does ext-uv also have some custom pgsql support which he could use for inspiration? The native loop driver also works just fine...

The readme of this package says that it's incompatible with ext-ev. Is that true or was it actually meant to say that it's incompatible with ext-event? Or is it with both?

@kelunik @trowski @bwoebi

**Comment by enumag** [comment]
bump

**Comment by trowski** [comment]
Sorry I can't provide any insight, as I've always used ext-pq in production, so I don't have much experience using ext-pgsql. Maybe @bwoebi would know if he had to add support to ext-uv specifically for ext-pgsql.

**Comment by enumag** [comment]
Thanks. Indeed ext-pq works fine!
