### ISSUE TITLE
Array of enum values is parsed as string instead of array

### ISSUE THREAD

**Issue by Bilge** [amphp/postgres#45]
```sql
CREATE TYPE "Foo" AS ENUM ('F1', 'F2', 'F3');
ALTER TABLE "myFoo" ADD COLUMN foos "Foo"[] NOT NULL DEFAULT '{}';
```

```php
$connection->execute('SELECT foos FROM "myFoo"');
```

* When foos is empty, I get the empty string (`'{}'`) instead of an empty array (`[]`).
* When foos is non-empty, I get a string (`'{F1}'`) instead of an array of strings (`['F1']`).

**Comment by trowski** [comment]
Fixed in https://github.com/amphp/postgres/commit/2479a0be5681453ab4f9455e038542204eaa7afb.
