### ISSUE TITLE
[feature request]: last insert oid

### ISSUE THREAD

**Issue by azjezz** [amphp/postgres#49]
The `pg` driver offers `pg_last_oid` function that can be used to retrieve the last oid from a result, however, amphp doesn't offer a high level access to this function ( similar to the `getLastInsertId` in amphp/mysql ), or access to the underlying result handle.

I think adding `getLastInsertId` would be a good start, while offering access to the underlying result handle ( or possible all types of handles, e.g: pg handle, socket connection, ... etc ) might be dangerous, it's a good feature to have that would allow people that know what they are doing to play around.

**Comment by azjezz** [comment]
ref: https://github.com/neutomic/neu/tree/feat/database

**Comment by trowski** [comment]
OIDs are not the same as MySQL's auto_increment columns: https://stackoverflow.com/questions/5625585/sql-postgres-oids-what-are-they-and-why-are-they-useful

To retrieve the last value of a sequence, use `RETURNING` on the query: https://www.postgresql.org/docs/14/dml-returning.html
