### ISSUE TITLE
PG Copy support

### ISSUE THREAD

**Issue by PNixx** [amphp/postgres#60]
Are there plans to implement the `pg_copy_from` method?

**Comment by trowski** [comment]
No. Unless I'm missing something, this seems like something which can be accomplished with `query` and writing the SQL manually.

**Comment by PNixx** [comment]
You won't be able to insert csv via `query` without access to the server. `pg_copy_from` just inserts an array of strings without the need to physically upload the file to the server from the database.

**Comment by trowski** [comment]
Ah, I see. Unfortunately, `pg_copy_from` is blocking, and no async equivalent is provided. I guess this would either need to be done in something like a parallel task, or as individual insert queries.
