### ISSUE TITLE
[v2.0.0-beta.5] Call to undefined method Amp\Postgres\Internal\PostgresPooledTransaction::createSavepoint()

### ISSUE THREAD

**Issue by PNixx** [amphp/postgres#63]
After update from v2.0.0-beta.4 method `createSavepoint()` not found:

```php
$transaction = $connection->beginTransaction();
$transaction->createSavepoint($name); // <-- here
```

**Comment by trowski** [comment]
Transactions no longer implement methods for savepoints. Instead, you can start a nested transaction using `PostgresTransaction::beginTransaction()` and use the returned `PostgresTransaction` as a `Link` object to perform queries within a savepoint.
