### ISSUE TITLE
Make new release?

### ISSUE THREAD

**Issue by prolic** [amphp/postgres#9]
v0.2.1 is pretty buggy and lot's of changes are in master - can you make a new dev-release (maybe v0.3)?

Also: Are there any plans to add an interface behind amphp/postgres & amphp/mysql, so I can chose to be compatible to both?

**Comment by trowski** [comment]
I've been using this library in development over the last few months and improving it along the way. The master branch is now running in production and seems very stable. I planned on seeing how production went for a few weeks and tag a 1.0.

I hadn't given a common interface any thought, as often the SQL queries have to differ between the two, so I'm not sure how swappable they really are in practice. @kelunik @bwoebi Any options on that?

**Comment by prolic** [comment]
I don't care if I had to use different queries really (I know there are some differences in Postgres / MySQL / MariaDB). I am totally fine with a switch statement and making a decision which query to use. The problem is, that I don't want to copy / paste a whole library, just to have a postgres and a mysql version of it. A switch statement to check which query to use is totally fine.

**Comment by mmasiukevich** [comment]
Maybe it's time to make a release version?
Just otherwise it is impossible to use the library in any of its projects. Especially when you consider that the master receives a non-working code (https://github.com/amphp/postgres/issues/15)

**Comment by kelunik** [comment]
I think we're pretty near to a release. `amphp/sql` is ready to be tagged IMO, we can tag this library shortly after if everything works fine.

**Comment by mmasiukevich** [comment]
> I think we're pretty near to a release. `amphp/sql` is ready to be tagged IMO, we can tag this library shortly after if everything works fine.

Thank you.
I have a framework that uses many of your components, but without versions it is very difficult to maintain its work.

**Comment by trowski** [comment]
`v1.0.0` just tagged. 😃
